"""baseline existing schema

Revision ID: c4647a9160ea
Revises: 
Create Date: 2026-05-28 01:35:45.964255
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'c4647a9160ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_quote',
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('pre_close', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('vol', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('turnover_rate', sa.Float(), nullable=True),
    sa.Column('float_share', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date')
    )
    op.create_table('industry_daily_report',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('report_json', sa.JSON(), nullable=True),
    sa.Column('model_provider', sa.String(length=32), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_daily_report_status'), 'industry_daily_report', ['status'], unique=False)
    op.create_index(op.f('ix_industry_daily_report_trade_date'), 'industry_daily_report', ['trade_date'], unique=True)
    op.create_table('intraday_scan_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pool_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('min_confirm_hits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_entity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('normalized_name', sa.String(length=128), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'normalized_name', name='uq_message_entity_type_name')
    )
    op.create_index(op.f('ix_message_entity_entity_type'), 'message_entity', ['entity_type'], unique=False)
    op.create_index(op.f('ix_message_entity_status'), 'message_entity', ['status'], unique=False)
    op.create_index(op.f('ix_message_entity_ts_code'), 'message_entity', ['ts_code'], unique=False)
    op.create_index('ix_message_entity_type_status', 'message_entity', ['entity_type', 'status'], unique=False)
    op.create_table('message_keyword_seed',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('keyword', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('theme', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword', 'type', 'theme', 'language', name='uq_message_keyword_seed')
    )
    op.create_index('ix_message_keyword_seed_theme_priority', 'message_keyword_seed', ['theme', 'priority'], unique=False)
    op.create_table('message_source_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('theme', sa.String(length=64), nullable=True),
    sa.Column('ts_code', sa.String(length=16), nullable=True),
    sa.Column('stock_name', sa.String(length=32), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.String(length=16), nullable=False),
    sa.Column('heat_score', sa.Integer(), nullable=False),
    sa.Column('credibility_score', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_source_item_channel'), 'message_source_item', ['channel'], unique=False)
    op.create_index('ix_message_source_item_date_stock', 'message_source_item', ['trade_date', 'ts_code'], unique=False)
    op.create_index('ix_message_source_item_date_theme', 'message_source_item', ['trade_date', 'theme'], unique=False)
    op.create_index(op.f('ix_message_source_item_dedupe_key'), 'message_source_item', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_message_source_item_theme'), 'message_source_item', ['theme'], unique=False)
    op.create_index(op.f('ix_message_source_item_trade_date'), 'message_source_item', ['trade_date'], unique=False)
    op.create_index(op.f('ix_message_source_item_ts_code'), 'message_source_item', ['ts_code'], unique=False)
    op.create_table('message_topic',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('theme', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('lifecycle_stage', sa.String(length=16), nullable=False),
    sa.Column('sentiment', sa.String(length=16), nullable=False),
    sa.Column('heat_score', sa.Integer(), nullable=False),
    sa.Column('credibility_score', sa.Integer(), nullable=False),
    sa.Column('crowding_score', sa.Integer(), nullable=False),
    sa.Column('source_platforms', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'theme', name='uq_message_topic_date_theme')
    )
    op.create_index(op.f('ix_message_topic_trade_date'), 'message_topic', ['trade_date'], unique=False)
    op.create_table('sector_basic',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sector_code', sa.String(length=32), nullable=False),
    sa.Column('sector_name', sa.String(length=64), nullable=False),
    sa.Column('sector_type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_code', sa.String(length=32), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('latest_pct_chg', sa.Float(), nullable=True),
    sa.Column('latest_hot', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_basic_sector_code'), 'sector_basic', ['sector_code'], unique=True)
    op.create_index(op.f('ix_sector_basic_sector_name'), 'sector_basic', ['sector_name'], unique=False)
    op.create_index(op.f('ix_sector_basic_sector_type'), 'sector_basic', ['sector_type'], unique=False)
    op.create_index(op.f('ix_sector_basic_source'), 'sector_basic', ['source'], unique=False)
    op.create_table('sector_daily_quote',
    sa.Column('sector_code', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('sector_name', sa.String(length=64), nullable=False),
    sa.Column('sector_type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('vol', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('turnover_rate', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sector_code', 'trade_date')
    )
    op.create_index(op.f('ix_sector_daily_quote_sector_name'), 'sector_daily_quote', ['sector_name'], unique=False)
    op.create_index(op.f('ix_sector_daily_quote_sector_type'), 'sector_daily_quote', ['sector_type'], unique=False)
    op.create_index(op.f('ix_sector_daily_quote_source'), 'sector_daily_quote', ['source'], unique=False)
    op.create_index('ix_sector_daily_type_date', 'sector_daily_quote', ['sector_type', 'trade_date'], unique=False)
    op.create_table('sector_quote_sync_state',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sector_code', sa.String(length=32), nullable=False),
    sa.Column('sector_name', sa.String(length=64), nullable=False),
    sa.Column('sector_type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target_days', sa.Integer(), nullable=True),
    sa.Column('quote_count', sa.Integer(), nullable=False),
    sa.Column('first_trade_date', sa.String(length=8), nullable=True),
    sa.Column('last_trade_date', sa.String(length=8), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_code', 'source', name='uq_sector_quote_sync_source')
    )
    op.create_index(op.f('ix_sector_quote_sync_state_sector_code'), 'sector_quote_sync_state', ['sector_code'], unique=False)
    op.create_index(op.f('ix_sector_quote_sync_state_sector_name'), 'sector_quote_sync_state', ['sector_name'], unique=False)
    op.create_index(op.f('ix_sector_quote_sync_state_sector_type'), 'sector_quote_sync_state', ['sector_type'], unique=False)
    op.create_index(op.f('ix_sector_quote_sync_state_source'), 'sector_quote_sync_state', ['source'], unique=False)
    op.create_index(op.f('ix_sector_quote_sync_state_status'), 'sector_quote_sync_state', ['status'], unique=False)
    op.create_index('ix_sector_quote_sync_status_retry', 'sector_quote_sync_state', ['status', 'next_retry_at'], unique=False)
    op.create_table('stock_ai_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('pool_id', sa.String(length=36), nullable=True),
    sa.Column('watch_stock_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('model_provider', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=True),
    sa.Column('analysis_json', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('data_trade_date', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_ai_analysis_code_created', 'stock_ai_analysis', ['ts_code', 'created_at'], unique=False)
    op.create_index(op.f('ix_stock_ai_analysis_data_trade_date'), 'stock_ai_analysis', ['data_trade_date'], unique=False)
    op.create_index(op.f('ix_stock_ai_analysis_pool_id'), 'stock_ai_analysis', ['pool_id'], unique=False)
    op.create_index(op.f('ix_stock_ai_analysis_ts_code'), 'stock_ai_analysis', ['ts_code'], unique=False)
    op.create_index(op.f('ix_stock_ai_analysis_watch_stock_id'), 'stock_ai_analysis', ['watch_stock_id'], unique=False)
    op.create_table('stock_basic',
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('area', sa.String(length=16), nullable=True),
    sa.Column('industry', sa.String(length=32), nullable=True),
    sa.Column('market', sa.String(length=16), nullable=True),
    sa.Column('list_date', sa.String(length=8), nullable=True),
    sa.Column('list_status', sa.String(length=2), nullable=True),
    sa.Column('float_share', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ts_code')
    )
    op.create_table('stock_sector_map',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('sector_code', sa.String(length=32), nullable=False),
    sa.Column('sector_name', sa.String(length=64), nullable=False),
    sa.Column('sector_type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'sector_code', 'source', name='uq_stock_sector_source')
    )
    op.create_index(op.f('ix_stock_sector_map_sector_code'), 'stock_sector_map', ['sector_code'], unique=False)
    op.create_index(op.f('ix_stock_sector_map_sector_name'), 'stock_sector_map', ['sector_name'], unique=False)
    op.create_index(op.f('ix_stock_sector_map_sector_type'), 'stock_sector_map', ['sector_type'], unique=False)
    op.create_index(op.f('ix_stock_sector_map_source'), 'stock_sector_map', ['source'], unique=False)
    op.create_index(op.f('ix_stock_sector_map_ts_code'), 'stock_sector_map', ['ts_code'], unique=False)
    op.create_index('ix_stock_sector_type_code', 'stock_sector_map', ['sector_type', 'sector_code'], unique=False)
    op.create_table('sync_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_detail',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('trade_time', sa.String(length=8), nullable=True),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('stamp_tax', sa.Float(), nullable=True),
    sa.Column('exec_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_plan',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('actual_pnl', sa.Float(), nullable=True),
    sa.Column('review_summary', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watch_pool',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_monitor_rule', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('trigger_target_pool_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industry_report_candidate',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('stock_name', sa.String(length=32), nullable=True),
    sa.Column('theme', sa.String(length=64), nullable=False),
    sa.Column('path_json', sa.JSON(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('path_score', sa.Integer(), nullable=False),
    sa.Column('evidence_score', sa.Integer(), nullable=False),
    sa.Column('heat_score', sa.Integer(), nullable=False),
    sa.Column('crowding_score', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['industry_daily_report.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'ts_code', 'theme', name='uq_industry_report_candidate')
    )
    op.create_index('ix_industry_candidate_date_score', 'industry_report_candidate', ['trade_date', 'final_score'], unique=False)
    op.create_index(op.f('ix_industry_report_candidate_grade'), 'industry_report_candidate', ['grade'], unique=False)
    op.create_index(op.f('ix_industry_report_candidate_report_id'), 'industry_report_candidate', ['report_id'], unique=False)
    op.create_index(op.f('ix_industry_report_candidate_theme'), 'industry_report_candidate', ['theme'], unique=False)
    op.create_index(op.f('ix_industry_report_candidate_trade_date'), 'industry_report_candidate', ['trade_date'], unique=False)
    op.create_index(op.f('ix_industry_report_candidate_ts_code'), 'industry_report_candidate', ['ts_code'], unique=False)
    op.create_table('message_opportunity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('theme', sa.String(length=64), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=True),
    sa.Column('stock_name', sa.String(length=32), nullable=True),
    sa.Column('opportunity_score', sa.Integer(), nullable=False),
    sa.Column('heat_score', sa.Integer(), nullable=False),
    sa.Column('credibility_score', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('action_suggestion', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('catalysts', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('source_platforms', sa.JSON(), nullable=True),
    sa.Column('source_links', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['message_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_opportunity_date_score', 'message_opportunity', ['trade_date', 'opportunity_score'], unique=False)
    op.create_index(op.f('ix_message_opportunity_trade_date'), 'message_opportunity', ['trade_date'], unique=False)
    op.create_index(op.f('ix_message_opportunity_ts_code'), 'message_opportunity', ['ts_code'], unique=False)
    op.create_table('message_relation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_entity_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=40), nullable=False),
    sa.Column('target_entity_id', sa.String(length=36), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('polarity', sa.String(length=16), nullable=False),
    sa.Column('valid_from', sa.String(length=8), nullable=True),
    sa.Column('valid_to', sa.String(length=8), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['message_entity.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['message_entity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_entity_id', 'relation_type', 'target_entity_id', 'source_type', name='uq_message_relation_edge_source')
    )
    op.create_index(op.f('ix_message_relation_relation_type'), 'message_relation', ['relation_type'], unique=False)
    op.create_index(op.f('ix_message_relation_source_entity_id'), 'message_relation', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_message_relation_status'), 'message_relation', ['status'], unique=False)
    op.create_index(op.f('ix_message_relation_target_entity_id'), 'message_relation', ['target_entity_id'], unique=False)
    op.create_index('ix_message_relation_type_status', 'message_relation', ['relation_type', 'status'], unique=False)
    op.create_table('trade_plan_stock',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('stock_name', sa.String(length=32), nullable=True),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('trigger_strategy', sa.Text(), nullable=True),
    sa.Column('planned_buy_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_loss_price', sa.Float(), nullable=True),
    sa.Column('risk_reward_ratio', sa.Float(), nullable=True),
    sa.Column('position_plan', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['trade_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watch_stock',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pool_id', sa.String(length=36), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('added_price', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('monitor_status', sa.String(length=16), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('ai_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('limit_up_date', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['watch_pool.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'ts_code', name='uq_pool_stock')
    )
    op.create_table('message_relation_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('relation_id', sa.String(length=36), nullable=False),
    sa.Column('source_item_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('evidence_url', sa.String(length=500), nullable=True),
    sa.Column('source_channel', sa.String(length=32), nullable=True),
    sa.Column('extraction_method', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['relation_id'], ['message_relation.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['message_source_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_relation_evidence_relation_created', 'message_relation_evidence', ['relation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_message_relation_evidence_relation_id'), 'message_relation_evidence', ['relation_id'], unique=False)
    op.create_index(op.f('ix_message_relation_evidence_source_item_id'), 'message_relation_evidence', ['source_item_id'], unique=False)
    op.create_table('monitor_rule',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pool_id', sa.String(length=36), nullable=True),
    sa.Column('stock_id', sa.String(length=36), nullable=True),
    sa.Column('template_id', sa.String(length=32), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('logic', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['watch_pool.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['watch_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('stock_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('trigger_date', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('buy_strategy_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['trade_plan.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['monitor_rule.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['watch_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert')
    op.drop_table('monitor_rule')
    op.drop_index(op.f('ix_message_relation_evidence_source_item_id'), table_name='message_relation_evidence')
    op.drop_index(op.f('ix_message_relation_evidence_relation_id'), table_name='message_relation_evidence')
    op.drop_index('ix_message_relation_evidence_relation_created', table_name='message_relation_evidence')
    op.drop_table('message_relation_evidence')
    op.drop_table('watch_stock')
    op.drop_table('trade_plan_stock')
    op.drop_index('ix_message_relation_type_status', table_name='message_relation')
    op.drop_index(op.f('ix_message_relation_target_entity_id'), table_name='message_relation')
    op.drop_index(op.f('ix_message_relation_status'), table_name='message_relation')
    op.drop_index(op.f('ix_message_relation_source_entity_id'), table_name='message_relation')
    op.drop_index(op.f('ix_message_relation_relation_type'), table_name='message_relation')
    op.drop_table('message_relation')
    op.drop_index(op.f('ix_message_opportunity_ts_code'), table_name='message_opportunity')
    op.drop_index(op.f('ix_message_opportunity_trade_date'), table_name='message_opportunity')
    op.drop_index('ix_message_opportunity_date_score', table_name='message_opportunity')
    op.drop_table('message_opportunity')
    op.drop_index(op.f('ix_industry_report_candidate_ts_code'), table_name='industry_report_candidate')
    op.drop_index(op.f('ix_industry_report_candidate_trade_date'), table_name='industry_report_candidate')
    op.drop_index(op.f('ix_industry_report_candidate_theme'), table_name='industry_report_candidate')
    op.drop_index(op.f('ix_industry_report_candidate_report_id'), table_name='industry_report_candidate')
    op.drop_index(op.f('ix_industry_report_candidate_grade'), table_name='industry_report_candidate')
    op.drop_index('ix_industry_candidate_date_score', table_name='industry_report_candidate')
    op.drop_table('industry_report_candidate')
    op.drop_table('watch_pool')
    op.drop_table('trade_plan')
    op.drop_table('trade_detail')
    op.drop_table('sync_log')
    op.drop_index('ix_stock_sector_type_code', table_name='stock_sector_map')
    op.drop_index(op.f('ix_stock_sector_map_ts_code'), table_name='stock_sector_map')
    op.drop_index(op.f('ix_stock_sector_map_source'), table_name='stock_sector_map')
    op.drop_index(op.f('ix_stock_sector_map_sector_type'), table_name='stock_sector_map')
    op.drop_index(op.f('ix_stock_sector_map_sector_name'), table_name='stock_sector_map')
    op.drop_index(op.f('ix_stock_sector_map_sector_code'), table_name='stock_sector_map')
    op.drop_table('stock_sector_map')
    op.drop_table('stock_basic')
    op.drop_index(op.f('ix_stock_ai_analysis_watch_stock_id'), table_name='stock_ai_analysis')
    op.drop_index(op.f('ix_stock_ai_analysis_ts_code'), table_name='stock_ai_analysis')
    op.drop_index(op.f('ix_stock_ai_analysis_pool_id'), table_name='stock_ai_analysis')
    op.drop_index(op.f('ix_stock_ai_analysis_data_trade_date'), table_name='stock_ai_analysis')
    op.drop_index('ix_stock_ai_analysis_code_created', table_name='stock_ai_analysis')
    op.drop_table('stock_ai_analysis')
    op.drop_index('ix_sector_quote_sync_status_retry', table_name='sector_quote_sync_state')
    op.drop_index(op.f('ix_sector_quote_sync_state_status'), table_name='sector_quote_sync_state')
    op.drop_index(op.f('ix_sector_quote_sync_state_source'), table_name='sector_quote_sync_state')
    op.drop_index(op.f('ix_sector_quote_sync_state_sector_type'), table_name='sector_quote_sync_state')
    op.drop_index(op.f('ix_sector_quote_sync_state_sector_name'), table_name='sector_quote_sync_state')
    op.drop_index(op.f('ix_sector_quote_sync_state_sector_code'), table_name='sector_quote_sync_state')
    op.drop_table('sector_quote_sync_state')
    op.drop_index('ix_sector_daily_type_date', table_name='sector_daily_quote')
    op.drop_index(op.f('ix_sector_daily_quote_source'), table_name='sector_daily_quote')
    op.drop_index(op.f('ix_sector_daily_quote_sector_type'), table_name='sector_daily_quote')
    op.drop_index(op.f('ix_sector_daily_quote_sector_name'), table_name='sector_daily_quote')
    op.drop_table('sector_daily_quote')
    op.drop_index(op.f('ix_sector_basic_source'), table_name='sector_basic')
    op.drop_index(op.f('ix_sector_basic_sector_type'), table_name='sector_basic')
    op.drop_index(op.f('ix_sector_basic_sector_name'), table_name='sector_basic')
    op.drop_index(op.f('ix_sector_basic_sector_code'), table_name='sector_basic')
    op.drop_table('sector_basic')
    op.drop_index(op.f('ix_message_topic_trade_date'), table_name='message_topic')
    op.drop_table('message_topic')
    op.drop_index(op.f('ix_message_source_item_ts_code'), table_name='message_source_item')
    op.drop_index(op.f('ix_message_source_item_trade_date'), table_name='message_source_item')
    op.drop_index(op.f('ix_message_source_item_theme'), table_name='message_source_item')
    op.drop_index(op.f('ix_message_source_item_dedupe_key'), table_name='message_source_item')
    op.drop_index('ix_message_source_item_date_theme', table_name='message_source_item')
    op.drop_index('ix_message_source_item_date_stock', table_name='message_source_item')
    op.drop_index(op.f('ix_message_source_item_channel'), table_name='message_source_item')
    op.drop_table('message_source_item')
    op.drop_index('ix_message_keyword_seed_theme_priority', table_name='message_keyword_seed')
    op.drop_table('message_keyword_seed')
    op.drop_index('ix_message_entity_type_status', table_name='message_entity')
    op.drop_index(op.f('ix_message_entity_ts_code'), table_name='message_entity')
    op.drop_index(op.f('ix_message_entity_status'), table_name='message_entity')
    op.drop_index(op.f('ix_message_entity_entity_type'), table_name='message_entity')
    op.drop_table('message_entity')
    op.drop_table('intraday_scan_config')
    op.drop_index(op.f('ix_industry_daily_report_trade_date'), table_name='industry_daily_report')
    op.drop_index(op.f('ix_industry_daily_report_status'), table_name='industry_daily_report')
    op.drop_table('industry_daily_report')
    op.drop_table('daily_quote')
    # ### end Alembic commands ###
